export const manifest = {
  images: [
    { key: 'ninja_sprite', url: 'assets/sprites/ninja.png' },
    { key: 'bg_forest', url: 'assets/backgrounds/bg_forest.png' },
    { key: 'bg_beach', url: 'assets/backgrounds/bg_beach.png' },
    { key: 'bg_castle', url: 'assets/backgrounds/bg_castle.png' },
  ],
  svgs: [
    { key: 'player_wave', url: 'assets/sprites/player_wave.svg', svgConfig: { width: 60, height: 60 } },
    { key: 'enemy_guard', url: 'assets/sprites/enemy_guard.svg', svgConfig: { width: 80, height: 80 } },
    { key: 'enemy_axe', url: 'assets/sprites/enemy_axe.svg', svgConfig: { width: 110, height: 80 } },
    { key: 'enemy_ninja', url: 'assets/sprites/enemy_ninja.svg', svgConfig: { width: 80, height: 80 } },
    { key: 'enemy_sniper', url: 'assets/sprites/enemy_sniper.svg', svgConfig: { width: 90, height: 80 } },
    { key: 'projectile', url: 'assets/sprites/projectile.svg', svgConfig: { width: 40, height: 20 } },
    { key: 'boss_idle', url: 'assets/sprites/boss_idle.svg', svgConfig: { width: 140, height: 120 } },
    { key: 'boss_attack', url: 'assets/sprites/boss_attack.svg', svgConfig: { width: 220, height: 120 } },
    { key: 'boss_rush', url: 'assets/sprites/boss_rush.svg', svgConfig: { width: 160, height: 120 } },
    { key: 'boss_windup', url: 'assets/sprites/boss_windup.svg', svgConfig: { width: 140, height: 120 } },
    { key: 'platform', url: 'assets/backgrounds/platform.svg', svgConfig: { width: 64, height: 64 } },
  ],
  spritesheets: [
    { key: 'player_idle_sheet', url: 'assets/sprites/player_idle_sheet.svg', frameConfig: { frameWidth: 120, frameHeight: 120 } },
    { key: 'player_run_sheet', url: 'assets/sprites/player_run_sheet.svg', frameConfig: { frameWidth: 120, frameHeight: 120 } },
    { key: 'player_jump_sheet', url: 'assets/sprites/player_jump_sheet.svg', frameConfig: { frameWidth: 120, frameHeight: 120 } },
    { key: 'player_fall_sheet', url: 'assets/sprites/player_fall_sheet.svg', frameConfig: { frameWidth: 120, frameHeight: 120 } },
    { key: 'player_dash_sheet', url: 'assets/sprites/player_dash_sheet.svg', frameConfig: { frameWidth: 120, frameHeight: 120 } },
    { key: 'player_defend_sheet', url: 'assets/sprites/player_defend_sheet.svg', frameConfig: { frameWidth: 120, frameHeight: 120 } },
    { key: 'player_combo1_sheet', url: 'assets/sprites/player_combo1_sheet.svg', frameConfig: { frameWidth: 120, frameHeight: 120 } },
    { key: 'player_combo2_sheet', url: 'assets/sprites/player_combo2_sheet.svg', frameConfig: { frameWidth: 120, frameHeight: 120 } },
    { key: 'player_combo3_sheet', url: 'assets/sprites/player_combo3_sheet.svg', frameConfig: { frameWidth: 120, frameHeight: 120 } },
    { key: 'player_combo4_sheet', url: 'assets/sprites/player_combo4_sheet.svg', frameConfig: { frameWidth: 120, frameHeight: 120 } },
    { key: 'player_wave_sheet', url: 'assets/sprites/player_wave_sheet.svg', frameConfig: { frameWidth: 120, frameHeight: 120 } },
    { key: 'player_uppercut_sheet', url: 'assets/sprites/player_uppercut_sheet.svg', frameConfig: { frameWidth: 120, frameHeight: 120 } },
    { key: 'player_dive_sheet', url: 'assets/sprites/player_dive_sheet.svg', frameConfig: { frameWidth: 120, frameHeight: 120 } },
    { key: 'player_hurt_sheet', url: 'assets/sprites/player_hurt_sheet.svg', frameConfig: { frameWidth: 120, frameHeight: 120 } },
  ]
} as const;
