export const manifest = {
  images: [
    { key: 'ninja_sprite', url: 'assets/sprites/ninja.png' },
    { key: 'bg_forest', url: 'assets/backgrounds/bg_forest.png' },
    { key: 'bg_beach', url: 'assets/backgrounds/bg_beach.png' },
    { key: 'bg_castle', url: 'assets/backgrounds/bg_castle.png' },
  ],
  svgs: [
    { key: 'player_wave', url: 'assets/sprites/player_wave.svg', svgConfig: { width: 60, height: 60 } },
    { key: 'projectile', url: 'assets/sprites/projectile.svg', svgConfig: { width: 40, height: 20 } },
    { key: 'platform', url: 'assets/backgrounds/platform.svg', svgConfig: { width: 64, height: 64 } },
    { key: 'bg_forest_far', url: 'assets/backgrounds/bg_forest_far.svg', svgConfig: { width: 1280, height: 720 } },
    { key: 'bg_forest_mid', url: 'assets/backgrounds/bg_forest_mid.svg', svgConfig: { width: 1280, height: 720 } },
    { key: 'bg_city_far', url: 'assets/backgrounds/bg_city_far.svg', svgConfig: { width: 1280, height: 720 } },
    { key: 'bg_city_mid', url: 'assets/backgrounds/bg_city_mid.svg', svgConfig: { width: 1280, height: 720 } },
    { key: 'bg_core_far', url: 'assets/backgrounds/bg_core_far.svg', svgConfig: { width: 1280, height: 720 } },
    { key: 'bg_core_mid', url: 'assets/backgrounds/bg_core_mid.svg', svgConfig: { width: 1280, height: 720 } },
  ],
  spritesheets: [
    { key: 'player_idle_sheet', url: 'assets/sprites/player_idle_sheet.svg', frameConfig: { frameWidth: 120, frameHeight: 120 } },
    { key: 'player_run_sheet', url: 'assets/sprites/player_run_sheet.svg', frameConfig: { frameWidth: 120, frameHeight: 120 } },
    { key: 'player_jump_sheet', url: 'assets/sprites/player_jump_sheet.svg', frameConfig: { frameWidth: 120, frameHeight: 120 } },
    { key: 'player_fall_sheet', url: 'assets/sprites/player_fall_sheet.svg', frameConfig: { frameWidth: 120, frameHeight: 120 } },
    { key: 'player_dash_sheet', url: 'assets/sprites/player_dash_sheet.svg', frameConfig: { frameWidth: 120, frameHeight: 120 } },
    { key: 'player_defend_sheet', url: 'assets/sprites/player_defend_sheet.svg', frameConfig: { frameWidth: 120, frameHeight: 120 } },
    { key: 'player_combo1_sheet', url: 'assets/sprites/player_combo1_sheet.svg', frameConfig: { frameWidth: 120, frameHeight: 120 } },
    { key: 'player_combo2_sheet', url: 'assets/sprites/player_combo2_sheet.svg', frameConfig: { frameWidth: 120, frameHeight: 120 } },
    { key: 'player_combo3_sheet', url: 'assets/sprites/player_combo3_sheet.svg', frameConfig: { frameWidth: 120, frameHeight: 120 } },
    { key: 'player_combo4_sheet', url: 'assets/sprites/player_combo4_sheet.svg', frameConfig: { frameWidth: 120, frameHeight: 120 } },
    { key: 'player_wave_sheet', url: 'assets/sprites/player_wave_sheet.svg', frameConfig: { frameWidth: 120, frameHeight: 120 } },
    { key: 'player_uppercut_sheet', url: 'assets/sprites/player_uppercut_sheet.svg', frameConfig: { frameWidth: 120, frameHeight: 120 } },
    { key: 'player_dive_sheet', url: 'assets/sprites/player_dive_sheet.svg', frameConfig: { frameWidth: 120, frameHeight: 120 } },
    { key: 'player_hurt_sheet', url: 'assets/sprites/player_hurt_sheet.svg', frameConfig: { frameWidth: 120, frameHeight: 120 } },
    // Enemies
    { key: 'enemy_guard_sheet', url: 'assets/sprites/enemy_guard_sheet.svg', frameConfig: { frameWidth: 120, frameHeight: 120 } },
    { key: 'enemy_guard_attack_sheet', url: 'assets/sprites/enemy_guard_attack_sheet.svg', frameConfig: { frameWidth: 120, frameHeight: 120 } },
    { key: 'enemy_axe_sheet', url: 'assets/sprites/enemy_axe_sheet.svg', frameConfig: { frameWidth: 150, frameHeight: 150 } },
    { key: 'enemy_axe_windup_sheet', url: 'assets/sprites/enemy_axe_windup_sheet.svg', frameConfig: { frameWidth: 150, frameHeight: 150 } },
    { key: 'enemy_axe_attack_sheet', url: 'assets/sprites/enemy_axe_attack_sheet.svg', frameConfig: { frameWidth: 150, frameHeight: 150 } },
    { key: 'enemy_ninja_sheet', url: 'assets/sprites/enemy_ninja_sheet.svg', frameConfig: { frameWidth: 120, frameHeight: 120 } },
    { key: 'enemy_ninja_attack_sheet', url: 'assets/sprites/enemy_ninja_attack_sheet.svg', frameConfig: { frameWidth: 120, frameHeight: 120 } },
    { key: 'enemy_sniper_sheet', url: 'assets/sprites/enemy_sniper_sheet.svg', frameConfig: { frameWidth: 120, frameHeight: 120 } },
    { key: 'enemy_sniper_shoot_sheet', url: 'assets/sprites/enemy_sniper_shoot_sheet.svg', frameConfig: { frameWidth: 120, frameHeight: 120 } },
    // Boss
    { key: 'boss_idle_sheet', url: 'assets/sprites/boss_idle_sheet.svg', frameConfig: { frameWidth: 256, frameHeight: 256 } },
    { key: 'boss_walk_sheet', url: 'assets/sprites/boss_walk_sheet.svg', frameConfig: { frameWidth: 256, frameHeight: 256 } },
    { key: 'boss_windup_sheet', url: 'assets/sprites/boss_windup_sheet.svg', frameConfig: { frameWidth: 256, frameHeight: 256 } },
    { key: 'boss_attack_sheet', url: 'assets/sprites/boss_attack_sheet.svg', frameConfig: { frameWidth: 256, frameHeight: 256 } },
    { key: 'boss_rush_sheet', url: 'assets/sprites/boss_rush_sheet.svg', frameConfig: { frameWidth: 256, frameHeight: 256 } },
  ]
} as const;
